name: Build, test and push

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  run_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x
          
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

  docker:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up QUEMU
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: aarontas8/goodweather:app-${{ github.sha }}
        file: .docker/Dockerfile
     
