name: Build, test and push

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  run_tests:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x

    - name: Build application
      run: |
        dotnet build -c Release
          
    - name: Run tests
      run: |
          dotnet test -c Release --logger trx --collect:"XPlat Code Coverage" --results-directory "./test-results"

    - name: Parse tests output (trx files)
      uses: NasAmin/trx-parser@v0.2.0
      id: trx-parser
      with:
        TRX_PATH: ./test-results
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up QUEMU
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: aarontas8/goodweather:app-${{ github.sha }}
        file: Dockerfile
     
  update_manifest:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Setup ArgoCD repository
      uses: actions/checkout@v3
      with:
        repository: 'aarontas/tfg-argocd'
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update manifest
      run: |
        echo "Updating manifest"
        git config user.email aaron_tas8@hotmail.com
        git config user.name aarontas
        cat apps/goodweather/goodweather-app-deployment.yaml
        sed -i "s+aarontas8/goodweather.*+aarontas8/goodweather:app-$RUN_NUMBER+g" apps/goodweather/goodweather-app-deployment.yaml
        cat apps/goodweather/goodweather-app-deployment.yaml
        git add .
        git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
        git push origin main
      
      env:
        RUN_NUMBER: ${{ github.run_number }}

     
